[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

[build]
  command = ""
  publish = "."

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

